#
# LateBindingApi project
# AppVeyor configuration
#

version: '0.9.0.{build}-alpha'

branches:
  except:
    - gh-pages

os: Visual Studio 2019

platform: Any CPU
configuration:
  - Release
  - Debug

assembly_info:
  patch: true
  file: AssemblySharedInfo.cs
  assembly_version: '0.9.0.{build}'
  assembly_file_version: '0.9.0.{build}'
  assembly_informational_version: '{version} ({branch})'

before_build:
  - cmd: nuget restore LateBindingApi.sln

build:
  project: LateBindingApi.sln
  verbosity: normal

test: off

before_package:
  - 7z a artifacts\LateBindingApp_v%APPVEYOR_BUILD_VERSION%.zip "%APPVEYOR_BUILD_FOLDER%\LateBindingGui\bin\%CONFIGURATION%\*" -xr!*.xml

artifacts:
  - path: 'artifacts\*.zip'

cache:
  - packages -> **\packages.config
