# NetOffice LateBinding project build pipeline

pool:
  vmImage: 'windows-2019'

variables:
  solution: LateBindingApi.sln

strategy:
  maxParallel: 2
  matrix:
    Debug:
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Debug'
    Release:
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    steps:
    - task: NuGetToolInstaller@0

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      displayName: Run Unit Tests (CodeGenerator)
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          CodeGenerator.UnitTests.dll
        searchFolder: Tests\CodeGenerator.UnitTests\bin\$(buildConfiguration)