# NetOffice LateBinding project build pipeline

pool:
  vmImage: 'windows-2019'

variables:
  solution: LateBindingApi.sln

resources:
  repositories:
  - repository: NetOfficeData
    type: github
    endpoint: NetOfficeFw
    name: NetOfficeFw/NetOffice-Data

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    strategy:
      maxParallel: 2
      matrix:
        Debug:
          buildPlatform: 'Any CPU'
          buildConfiguration: 'Debug'
        Release:
          buildPlatform: 'Any CPU'
          buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@0

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      displayName: Run Unit Tests (CodeGenerator)
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          CodeGenerator.UnitTests.dll
        searchFolder: Tests\CodeGenerator.UnitTests\bin\$(buildConfiguration)

    - task: PublishPipelineArtifact@1
      condition: eq(variables['buildConfiguration'], 'Release')
      inputs:
        artifactName: 'codegen'
        targetPath: '$(Build.SourcesDirectory)\CodeGen\bin\$(buildConfiguration)'

- stage: integration_tests
  displayName: Integration Tests
  condition: succeeded()
  jobs:
  - job: RunTests
    steps:
    - checkout: NetOfficeData
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: 'codegen'
        targetPath: '$(Build.BinariesDirectory)\codegen'
    - script: |
        set PATH="$(Build.BinariesDirectory)\codegen";%PATH%
        set NETOFFICE_DATA=$(Build.SourcesDirectory)\NetOffice-Data
        codegen.exe --project "%NETOFFICE_DATA%\src" --ref "%NETOFFICE_DATA%\bld\ReferenceIndex2.xml" --keyfiles "%NETOFFICE_DATA%\bld\KeyFiles" --output out
      workingDirectory: '$(Build.StagingDirectory)'
    - publish: $(Build.StagingDirectory)/out
      artifact: NetOffice_GeneratedCode_b$(Build.BuildId)