# NetOffice LateBinding project build pipeline

pool:
  vmImage: 'windows-2019'

variables:
  solution: LateBindingApi.sln

resources:
  repositories:
  - repository: NetOfficeData
    type: github
    endpoint: NetOfficeFw
    name: NetOfficeFw/NetOffice-Data

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    strategy:
      maxParallel: 2
      matrix:
        Debug:
          buildPlatform: 'Any CPU'
          buildConfiguration: 'Debug'
        Release:
          buildPlatform: 'Any CPU'
          buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@0

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      displayName: Run Unit Tests (CodeGenerator)
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          CodeGenerator.UnitTests.dll
        searchFolder: Tests\CodeGenerator.UnitTests\bin\$(buildConfiguration)

    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'codegen'
        targetPath: '$(Build.SourcesDirectory)\CodeGen\bin\$(buildConfiguration)'

- stage: integration_tests
  displayName: Integration Tests
  condition: and(succeeded(), eq(variables['buildConfiguration'], 'Release'))
  jobs:
  - job: RunTests
    steps:
    - checkout: NetOfficeData
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: 'codegen'
        targetPath: '$(Build.ArtifactStagingDirectory)\codegen'
