Imports System.Reflection
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
Imports NetOffice

  
'    Generated by LateBindingApi.CodeGenerator
'    http://latebindingapi.codeplex.com 
    
'    Contains the following Type Libraries:
'%List%


<Assembly: AssemblyTitle("%Title%")> 
<Assembly: AssemblyDescription("%Description%")> 
<Assembly: AssemblyConfiguration("%Configuration%")> 
<Assembly: AssemblyCompany("%Company%")> 
<Assembly: AssemblyProduct("%Product%")> 
<Assembly: AssemblyCopyright("%Copyright%")> 
<Assembly: AssemblyTrademark("%Trademark%")> 
<Assembly: AssemblyCulture("%Culture%")> 
<Assembly: AssemblyVersion("%Version%")> 
<Assembly: AssemblyFileVersion("%FileVersion%")> 
<Assembly: ComVisibleAttribute(false)> 
<Assembly: LateBindingAttribute("1.0")> 

'Alias Table
' 
'%AliasInclude%