using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;
using System.Text;

namespace LateBindingApi.CodeGenerator.CSharp
{
    internal static class CoClassApi
    {
        private static string _fileHeader = "//Generated by LateBindingApi.CodeGenerator\r\n"
                                      + "using System;\r\n"
                                      + "using NetRuntimeSystem = System;\r\n"
                                      + "using LateBindingApi.Core;\r\n"
                                      + "namespace %namespace%\r\n"
                                      + "{\r\n";

        private static string _classDesc = "\t///<summary>\r\n\t/// CoClass %name%\r\n\t///</summary>\r\n";

        private static string _classHeader = "\tpublic class %name% : %inherited%\r\n\t{\r\n";

        private static string _classConstructor;
       
        internal static string ConvertCoClassesToFiles(XElement projectNode, XElement classesNode, Settings settings, string solutionFolder)
        {
            string faceFolder = System.IO.Path.Combine(solutionFolder, projectNode.Attribute("Name").Value);
            faceFolder = System.IO.Path.Combine(faceFolder, "Classes");
            if (false == System.IO.Directory.Exists(faceFolder))
                System.IO.Directory.CreateDirectory(faceFolder);

            string result = "";
            foreach (XElement faceNode in classesNode.Elements("CoClass"))
                result += ConvertCoClassToFile(projectNode, faceNode, faceFolder) + "\r\n";

            return result;
        }

        private static string ConvertCoClassToFile(XElement projectNode, XElement classNode, string classFolder)
        {
            string fileName = System.IO.Path.Combine(classFolder, classNode.Attribute("Name").Value + ".cs");

            string newEnum = ConvertCoClassToString(projectNode, classNode);
            System.IO.File.AppendAllText(fileName, newEnum);

            int i = classFolder.LastIndexOf("\\");
            string result = "\t\t<Compile Include=\"" + classFolder.Substring(i + 1) + "\\" + classNode.Attribute("Name").Value + ".cs" + "\" />";
            return result;
        }

        private static string ConvertCoClassToString(XElement projectNode, XElement classNode)
        {
            string result = _fileHeader.Replace("%namespace%", projectNode.Attribute("Namespace").Value);
            string attributes = "\t" + CSharpGenerator.GetSupportByLibraryAttribute(classNode);
            string header = _classHeader.Replace("%name%", classNode.Attribute("Name").Value);
            header = header.Replace("%inherited%", GetInherited(projectNode, classNode));
            if (null == _classConstructor)
                _classConstructor = RessourceApi.ReadString("CoClass.Constructor.txt");
            string construct = _classConstructor.Replace("%name%", classNode.Attribute("Name").Value);
            construct = construct.Replace("%ProgId%", projectNode.Attribute("Name").Value + "." + classNode.Attribute("Name").Value);
            string classDesc = _classDesc.Replace("%name%", classNode.Attribute("Name").Value);
           
            result += classDesc;
            result += attributes + "\r\n";
            result += header;
            result += construct;

            result += "\t}\r\n}";
            return result;
        }

        private static string GetInherited(XElement projectNode, XElement faceNode)
        {
            if (faceNode.Element("Inherited").Elements("Ref").Count() == 0)
                return "COMObject";

            string retList = "";

            // select last default interface
            XElement refNode = faceNode.Element("DefaultInterfaces").Elements("Ref").Last();
            XElement inInterface = GetItemByKey(projectNode, refNode);
            if (inInterface.Parent.Parent == faceNode.Parent.Parent)
            {
                // same project               
                retList += inInterface.Attribute("Name").Value;
            }
            else
            {
                // extern project
                retList += inInterface.Parent.Parent.Attribute("Namespace").Value + "." + inInterface.Attribute("Name").Value;
            }

            return retList;
        }

        private static XElement GetItemByKey(XElement projectNode, XElement refEntity)
        {
            XElement solutionNode = projectNode.Parent.Parent;
            string key = refEntity.Attribute("Key").Value;
            foreach (var project in solutionNode.Element("Projects").Elements("Project"))
            {
                var target = (from a in project.Element("Interfaces").Elements("Interface")
                              where a.Attribute("Key").Value.Equals(key, StringComparison.InvariantCultureIgnoreCase)
                              select a).FirstOrDefault();
                if (null != target)
                    return target;

                target = (from a in project.Element("DispatchInterfaces").Elements("Interface")
                          where a.Attribute("Key").Value.Equals(key, StringComparison.InvariantCultureIgnoreCase)
                          select a).FirstOrDefault();
                if (null != target)
                    return target;

                target = (from a in project.Element("CoClasses").Elements("CoClass")
                          where a.Attribute("Key").Value.Equals(key, StringComparison.InvariantCultureIgnoreCase)
                          select a).FirstOrDefault();
                if (null != target)
                    return target;
            }

            throw (new ArgumentException("refEntity not found."));
        }
    }
}
