using System;

namespace NetOfficeVerify
{
    public class GeneratorTestContext
    {
        public GeneratorTestContext()
        {
            this.GeneratedCodeDir = @"d:\dev\github\NetOfficeFw\LateBinding\out\NetOffice";
            this.GoldCodeDir = @"d:\dev\github\NetOfficeFw\NetOffice-v1.7.4.x\Source";
        }

        /// <summary>
        /// Directory name with source code generated by LateBindingApi tool.
        /// </summary>
        public string GeneratedCodeDir { get; private set; }

        /// <summary>
        /// Directory name with gold source code of NetOffice project.
        /// </summary>
        public string GoldCodeDir { get; private set; }
    }
}
