using System;
using System.IO;
using System.Text;
using DiffMatchPatch;
using NUnit.Framework;

namespace NetOfficeVerify
{
    public abstract class ProjectTestContext
    {
        public ProjectTestContext(string projectName)
        {
            this.ProjectName = projectName;

            this.GeneratedProjectDir = @"c:\dev\github\NetOfficeFw\LateBindingApi.CodeGenerator\out\NetOffice\" + projectName;
            this.GoldProjectDir = @"c:\dev\github\NetOfficeFw\NetOffice-v1.7.4.3\Source\" + projectName;
        }

        /// <summary>
        /// Directory name with source code generated by LateBindingApi tool.
        /// </summary>
        public string GeneratedProjectDir { get; private set; }

        /// <summary>
        /// Directory name with gold source code of NetOffice project.
        /// </summary>
        public string GoldProjectDir { get; private set; }

        public string ProjectName { get; private set; }

        protected void VerifyCoClassDelegatesInFile(string filename)
        {
            var generatedFile = Path.Combine(this.GeneratedProjectDir, "Classes", filename);
            var goldFile = Path.Combine(this.GoldProjectDir, "Classes", filename);

            var actualDelegates = GetDelegatesFromFile(generatedFile);
            var expectedDelegates = GetDelegatesFromFile(goldFile);

            var dmp = new diff_match_patch();
            var diff = dmp.diff_main(expectedDelegates, actualDelegates);
            dmp.diff_cleanupSemantic(diff);

            if (diff.Count == 1)
            {
                if (diff[0].operation == Operation.EQUAL)
                {
                    // passed
                    return;
                }
            }

            if (diff.Count > 0)
            {
                var delta = dmp.diff_prettyText(diff);
                var batFilename = GenerateCommandFileForDiff(generatedFile, goldFile);

                var msg = $"Delegates in file {this.ProjectName}\\Classes\\{filename} does not match the gold file definition.\n\n" +
                          $"Run diff file:///{batFilename}\n\n" +
                          $"Changes:\n" +
                          $"{delta}\n\n" +
                          $"Gold file: {goldFile}";
                Assert.Fail(msg);
            }
        }

        protected string GetDelegatesFromFile(string path)
        {
            var sb = new StringBuilder();

            bool readDelegates = false;
            foreach (var line in File.ReadLines(path))
            {
                if (line.TrimStart().StartsWith("#region Delegates"))
                {
                    readDelegates = true;
                    continue;
                }

                if (readDelegates)
                {
                    if (line.TrimStart().StartsWith("#endregion"))
                    {
                        break;
                    }

                    sb.AppendLine(line);
                }
            }

            return sb.ToString();
        }

        private string GenerateCommandFileForDiff(string generatedFile, string goldFile)
        {
            var batFilename = Path.Combine(Path.GetTempPath(), "run_diff_"+ Path.GetRandomFileName() + ".bat");

            string commandLine = $@"WinMergeU.exe /u /e ""{generatedFile}"" ""{goldFile}""";
            File.WriteAllText(batFilename, commandLine);

            return batFilename;
        }
    }
}
